sudo: required

language: cpp

services:
 - docker

env:
  global:
    - OPEN62541_COMPAT_VERSION=OPCUA-2413-open62541-enhancements-for-mirror-variable-optional-module-compatibility

jobs:
  include:
    - name: open62541_default_quasar_design
      script:
        - docker run  --interactive --tty pnikiel/quasar:quasar_with_uasak /bin/bash -c "
            echo branch ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} ;
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} --depth=1 https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            .CI/run_test_case.py --opcua_backend o6 --open62541_compat_branch ${OPEN62541_COMPAT_VERSION} --compare_with_nodeset .CI/test_cases/test_default_quasar_design/reference_ns2.xml;
            "

    - name: open62541_test_cache_variables
      script:
        - docker run  --interactive --tty pnikiel/quasar:quasar_with_uasak /bin/bash -c "
            echo branch ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} ;
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} --depth=1 https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            .CI/run_test_case.py --opcua_backend o6 --open62541_compat_branch ${OPEN62541_COMPAT_VERSION} --design .CI/test_cases/test_cache_variables/Design.xml --generate_all_devices --config .CI/test_cases/test_cache_variables/config.xml;
            cp .CI/test_cases/test_cache_variables/DTestClass.test.h Device/include/DTestClass.h ;
            cp .CI/test_cases/test_cache_variables/DTestClass.test.cpp Device/src/DTestClass.cpp ;
            ./quasar.py build Release ;
            ./.CI/travis/server_fixture.py --command_to_run uasak_dump ;
            /opt/NodeSetTools/nodeset_compare.py .CI/test_cases/test_cache_variables/reference_ns2.xml build/bin/dump.xml --ignore_nodeids StandardMetaData ;
            "

    - name: open62541_test_recurrent_hasobjects
      script:
        - docker run  --interactive --tty pnikiel/quasar:quasar_with_uasak /bin/bash -c "
            echo branch ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} ;
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} --depth=1 https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            .CI/run_test_case.py --opcua_backend o6 --open62541_compat_branch ${OPEN62541_COMPAT_VERSION} --design .CI/test_cases/test_recurrent_hasobjects/Design.xml --generate_all_devices --config .CI/test_cases/test_recurrent_hasobjects/config.xml;
            "

    - name: open62541_test_single_variable_node
      script:
        - docker run  --interactive --tty pnikiel/quasar:quasar_with_uasak /bin/bash -c "
            echo branch ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} ;
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} --depth=1 https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            .CI/run_test_case.py --opcua_backend o6 --open62541_compat_branch ${OPEN62541_COMPAT_VERSION} --design .CI/test_cases/test_single_variable_node/Design.xml --generate_all_devices --config .CI/test_cases/test_single_variable_node/config.xml;
            "

    - name: open62541_test_methods
      script:
        - docker run  --interactive --tty pnikiel/quasar:quasar_with_uasak /bin/bash -c "
            echo branch ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} ;
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} --depth=1 https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            .CI/run_test_case.py --opcua_backend o6 --open62541_compat_branch ${OPEN62541_COMPAT_VERSION} --design .CI/test_cases/test_methods/Design.xml --generate_all_devices --config .CI/test_cases/test_methods/config.xml --compare_with_nodeset .CI/test_cases/test_methods/reference_ns2.xml ;
            "

    - name: open62541_test_instantiation_from_design
      script:
        - docker run  --interactive --tty pnikiel/quasar:quasar_with_uasak /bin/bash -c "
            echo branch ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} ;
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} --depth=1 https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            .CI/run_test_case.py --opcua_backend o6 --open62541_compat_branch ${OPEN62541_COMPAT_VERSION} --design .CI/test_cases/test_instantiation_from_design/Design.xml --generate_all_devices --config .CI/test_cases/test_instantiation_from_design/config.xml 
            "

    - name: open62541_test_config_entries
      script:
        - docker run  --interactive --tty pnikiel/quasar:quasar_with_uasak /bin/bash -c "
            echo branch ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} ;
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} --depth=1 https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            .CI/run_test_case.py --opcua_backend o6 --open62541_compat_branch ${OPEN62541_COMPAT_VERSION} --design .CI/test_cases/test_config_entries/Design.xml --generate_all_devices --config .CI/test_cases/test_config_entries/config.xml --compare_with_nodeset .CI/test_cases/test_config_entries/reference_ns2.xml
            "

    - name: open62541_test_config_restrictions
      script:
        - docker run  --interactive --tty pnikiel/quasar:quasar_with_uasak /bin/bash -c "
            echo branch ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} ;
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} --depth=1 https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            .CI/run_test_case.py --opcua_backend o6 --open62541_compat_branch ${OPEN62541_COMPAT_VERSION} --design .CI/test_cases/test_config_restrictions/Design.xml;"
