sudo: required

language: cpp

services:
 - docker

jobs:
  include:
    - name: open62541_default_quasar_design
      script:
        - docker run  --interactive --tty pnikiel/quasar:quasar_with_uasak /bin/bash -c "
            echo '********************************************************************' ;
            echo branch ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} ;
            echo '********************************************************************' ;
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            sh .CI/travis/job_epilogue.sh ;
            /opt/NodeSetTools/nodeset_compare.py .CI/test_cases/test_default_quasar_design/reference_ns2.xml build/bin/dump.xml ;

            "

    - name: open62541_test_cache_variables
      script:
        - docker run  --interactive --tty pnikiel/quasar:quasar_with_uasak /bin/bash -c "
            echo '********************************************************************' ;
            echo branch ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} ;
            echo '********************************************************************' ;
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            ./quasar.py enable_module open62541-compat OPCUA-2363_profit_from_uaprint ;
            ./quasar.py set_build_config open62541_config.cmake ;
            cp .CI/test_cases/test_cache_variables/Design.xml Design ;
            ./quasar.py generate device --all ;
            ./quasar.py build Release ;
            cp .CI/test_cases/test_cache_variables/DTestClass.test.h Device/include/DTestClass.h ;
            cp .CI/test_cases/test_cache_variables/DTestClass.test.cpp Device/src/DTestClass.cpp ;
            cp -v .CI/test_cases/test_cache_variables/config.xml build/bin ;
            ./quasar.py build Release ;
            ./.CI/travis/server_fixture.py --command_to_run uasak_dump ;
            /opt/NodeSetTools/nodeset_compare.py .CI/test_cases/test_cache_variables/reference_ns2.xml build/bin/dump.xml ;
            "

    - name: open62541_test_recurrent_hasobjects
      script:
        - docker run  --interactive --tty pnikiel/quasar:quasar_with_uasak /bin/bash -c "
            echo '********************************************************************' ;
            echo branch ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} ;
            echo '********************************************************************' ;
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            source .CI/travis/job_prologue.sh ;
            ./quasar.py enable_module open62541-compat OPCUA-2363_profit_from_uaprint ;
            ./quasar.py set_build_config open62541_config.cmake ;
            cp -v .CI/test_cases/test_recurrent_hasobjects/Design.xml Design ;
            ./quasar.py generate device --all ;
            cp -v .CI/test_cases/test_recurrent_hasobjects/config.xml bin/ ;
            ./quasar.py build Release ;
            ./.CI/travis/server_fixture.py --command_to_run uasak_dump ;"

    - name: open62541_test_single_variable_node
      script:
        - docker run  --interactive --tty pnikiel/quasar:quasar_with_uasak /bin/bash -c "
            echo '********************************************************************' ;
            echo branch ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} ;
            echo '********************************************************************' ;
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            source .CI/travis/job_prologue.sh ;
            ./quasar.py enable_module open62541-compat OPCUA-2363_profit_from_uaprint ;
            ./quasar.py set_build_config open62541_config.cmake ;
            cp -v .CI/test_cases/test_single_variable_node/Design.xml Design ;
            ./quasar.py generate device --all ;
            cp -v .CI/test_cases/test_single_variable_node/config.xml bin/ ;
            ./quasar.py build Release ;
            ./.CI/travis/server_fixture.py --command_to_run uasak_dump ;"

    - name: open62541_test_methods
      script:
        - docker run  --interactive --tty pnikiel/quasar:quasar_with_uasak /bin/bash -c "
            echo '********************************************************************' ;
            echo branch ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} ;
            echo '********************************************************************' ;
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            cp -v .CI/test_cases/test_methods/Design.xml Design ;
            ./quasar.py generate device --all ;
            cp -v .CI/test_cases/test_methods/config.xml bin/ ;
            source .CI/travis/job_epilogue.sh ;
            
            "

    - name: open62541_test_instantiation_from_design
      script:
        - docker run  --interactive --tty pnikiel/quasar:quasar_with_uasak /bin/bash -c "
            echo '********************************************************************' ;
            echo branch ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} ;
            echo '********************************************************************' ;
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            source .CI/travis/job_prologue.sh ;
            cp -v .CI/test_cases/test_instantiation_from_design/Design.xml Design ;
            ./quasar.py generate device --all ;
            cp -v .CI/test_cases/test_instantiation_from_design/config.xml bin/ ;
            source .CI/travis/job_epilogue.sh ;"

    - name: open62541_test_config_entries
      script:
        - docker run  --interactive --tty pnikiel/quasar:quasar_with_uasak /bin/bash -c "
            echo '********************************************************************' ;
            echo branch ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} ;
            echo '********************************************************************' ;
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            source .CI/travis/job_prologue.sh ;
            cp -v .CI/test_cases/test_config_entries/Design.xml Design ;
            ./quasar.py generate device --all ;
            cp -v .CI/test_cases/test_config_entries/config.xml bin/ ;
            source .CI/travis/job_epilogue.sh ;
            /opt/NodeSetTools/nodeset_compare.py .CI/test_cases/test_config_entries/reference_ns2.xml build/bin/dump.xml ;
            "

    - name: open62541_test_config_restrictions
      script:
        - docker run  --interactive --tty pnikiel/quasar:quasar_with_uasak /bin/bash -c "
            echo '********************************************************************' ;
            echo branch ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} ;
            echo '********************************************************************' ;
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            source .CI/travis/job_prologue.sh ;
            cp -v .CI/test_cases/test_config_restrictions/Design.xml Design ;
            source .CI/travis/job_epilogue.sh ;"
